package ru.tinkoff

    fun main(args: Array<String>) {
        var doggy=Dog("ПротоПёсель", -1)
        var dog=Dog("Пёсель", 4)
        var cat=Cat("Котяузер", 3)
        var parrot=Parrot("Кеша", 2)
        var snake=Snake("Зойберг", 5);
        var fish=Fish("Рыбусь", 1);
        doggy.getName()
        doggy.getAge()
        dog.voice()
        dog.getName()
        dog.getAge()
        dog.eat()
        dog.toClean()
        dog.eat()
        dog.walk()
        dog.eat()
        dog.eat()
        dog.eat()
        dog.walk()
        cat.voice()
        cat.getName()
        cat.getAge()
        cat.eat()
        cat.toClean()
        cat.eat()
        cat.toClean()
        cat.voice()
        cat.walk()
        cat.eat()
        parrot.voice()
        parrot.getName()
        parrot.getAge()
        parrot.fly()
        parrot.eat()
        cat.toClean()
        cat.eat()
        cat.eat()
        parrot.toClean()
        parrot.eat()
        parrot.eat()
        snake.voice()
        snake.getName()
        snake.getAge()
        snake.eat()
        snake.toClean()
        snake.eat()
        snake.crawl()
        snake.eat()
        snake.crawl()
        fish.swim()
        fish.getName()
        fish.getAge()
        fish.eat()
        fish.toClean()
        fish.eat()
        fish.eat()
        fish.eat()
        fish.askToEat()
    }
